rename "03. 数学分析(1~3) - Mathematical_Analysis_Paper"                     "05. 数学分析(1~3) - Mathematical_Analysis_Paper                    "       
rename "04. 高等代数(1~2) - Advanced_Algebra_NOTES"                          "06. 高等代数(1~2) - Advanced_Algebra_NOTES                         "       
rename "05. 解析几何 - Analytic_Geometry_NOTES"                              "07. 解析几何 - Analytic_Geometry_NOTES                             "       
rename "06. 常微分方程 - Ordinary_Differential_Equation_NOTES"               "08. 常微分方程 - Ordinary_Differential_Equation_NOTES              "        
rename "07. 概率统计 - Probability_Theory_and_Mathematical_Statistics_NOTES" "09. 概率统计 - Probability_Theory_and_Mathematical_Statistics_NOTES"       
rename "08. 数学建模 - Mathematical_Modeling_Report"                         "10. 数学建模 - Mathematical_Modeling_Report                        "       
rename "09. 数据结构与算法 - Data_Structure_and_Algorithm_Report"            "11. 数据结构与算法 - Data_Structure_and_Algorithm_Report           "          
rename "10. 信息论基础 - Elements_of_Information_Theory_Report"              "12. 信息论基础 - Elements_of_Information_Theory_Report             "        
rename "11. 数值计算方法 - Numerical_Calculation_Report"                     "13. 数值计算方法 - Numerical_Calculation_Report                    "         
rename "12. 离散数学 - Discrete_Mathematics_Report"                          "14. 离散数学 - Discrete_Mathematics_Report                         "       
rename "13. 高级语言程序设计 - C_Program_Design_Report"                      "15. 高级语言程序设计 - C_Program_Design_Report                     "           
rename "14. 操作系统 - Operating_System_Report"                              "16. 操作系统 - Operating_System_Report                             "       
rename "15. 近世代数 - Modern_Algebra_NOTES "                                "17. 近世代数 - Modern_Algebra_NOTES                                "       
rename "16. 编译原理 - Compile_Principles_NOTES"                             "18. 编译原理 - Compile_Principles_NOTES                            "       
rename "18. 运筹学通论 - Operations_Research_Report"                         "20. 运筹学通论 - Operations_Research_Report                        "        
rename "19. 数据库系统概论 - Database_System_Introduction_Report"            "21. 数据库系统概论 - Database_System_Introduction_Report           "          
rename "20. 数据挖掘与决策支持技术 - Data_Mining_Report"                     "22. 数据挖掘与决策支持技术 - Data_Mining_Report                    "              
rename "21. 现代密码学 - Modern_Cryptography_Report"                         "23. 现代密码学 - Modern_Cryptography_Report                        "        
rename "22. 计算机网络 - Computer_Network_Report"                            "24. 计算机网络 - Computer_Network_Report                           "        
rename "23. 微分方程数值解 - NumSln_of_DiffEq_Report"                        "25. 微分方程数值解 - NumSln_of_DiffEq_Report                       "          
rename "24. 算法图论 - Algorithm_of_Graph_Theory_Report"                     "26. 算法图论 - Algorithm_of_Graph_Theory_Report                    "       
rename "26. 科研规范训练 - Academic_Training_Paper"                          "28. 科研规范训练 - Academic_Training_Paper                         "         
rename "27. 毕业论文 - Thesis_for_Graduation_Paper"                          "29. 毕业论文 - Thesis_for_Graduation_Paper                         "
pause